version: "3.8"
services:
  db:
    image: mysql
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${mysql_pass}"
    ports:
      - "3306:3306"
    volumes:
      - example_db
      - type: bind
        source: ./data/reconstruct.sql
        target: /data/reconstruct.sql
      - type: bind
        source: ./.env
        target: /.env
    tty: true
    stdin_open: true
    networks: 
      - backend
  adminer:
    image: adminer:latest
    container_name: adminer_container
    restart: always
    environment:
      ADMINER_DESIGN: "rmsoft_blue"
    ports:
      - 8080:8080
    networks: 
      - backend
volumes:
  example_db:
networks: 
  backend:
    driver: bridge